name: 'Deploy Azure SQL Database schema'

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy_database_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Database Job
      uses: 
            actions/checkout@v2
            Azure/sql-action@v1.2
      
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        # uses dacpac to deploy database schema
        dacpac-package: './database/dacpac/bus-db.dacpac'